spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:searchdb
      driver-class-name: org.h2.Driver
      username: lsy
      password: 1234
  jwt:
    key: "Eijeij2d9j2kjf@(djud2qwfipj12!dip21jdpqwf2id"
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE